#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition 

count=1
while [ $count -le 21]
do
	echo $count
	case $counter in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((count++))
done
